Feature/back/connection
Escadev-SLDN2/JukeBox pull request #37
Opened 2020-02-11 16:21 UTC by Bastien-Baloup

gestion du formulaire de connexion

2020-02-12 15:14 UTC, lescadev requested changes
Ajouter la création d'un cookie, contenant l'id et le pseudo de l'utilisateur, pour : 

- vérifier que la connexion est effective
- réutiliser ce pseudo dans un éventuel message "bonjour pseudo"

2020-02-12 16:15 UTC, lescadev approved these changes

2020-02-13 11:00 UTC, JeremiaLateve approved these changes

2020-02-13 11:00 UTC, CBaraka approved these changes

2020-02-13 11:00 UTC, camille-avignon approved these changes

2020-02-13 11:00 UTC, Papibadiste approved these changes

2020-02-13 11:01 UTC, ghost approved these changes

2020-02-13 11:01 UTC, aboubacarkaba approved these changes

2020-02-13 11:01 UTC, DesirThomas approved these changes

2020-02-13 11:01 UTC, GermainA approved these changes

2020-02-13 11:01 UTC, merged