Fonctions reservées super utilisateur
Escadev-SLDN2/JukeBox pull request #59
Opened 2020-02-20 15:17 UTC by GermainA

2020-02-20 15:18 UTC, margotdessery approved these changes

2020-02-20 22:18 UTC, Bastien-Baloup commented on index.php
> +        <?php if ($iSUSet) { ?>
ou est définit $isSUSet ?

2020-02-20 22:18 UTC, Bastien-Baloup commented on index.php
> +        <?php if ($isSUSet) { ?>
idem

2020-02-21 15:31 UTC, aboubacarkaba approved these changes

2020-02-21 15:38 UTC, margotdessery approved these changes

2020-02-24 09:18 UTC, Samz87 approved these changes

2020-02-24 09:48 UTC, lescadev requested changes

2020-02-24 09:48 UTC, lescadev commented on index.php
> +                                    <?php if ($isSUSet) { ?>
1. on appelle une variable et non une méthode
2. il faut passer l'id de l'utilisateur courant dans l'appel de cette méthode
3. préférez la méthode d'intégration de PHP "inline" :
    `<?php if(blabla): ?>`
    `…`
    `<?php endif; ?>`

2020-02-24 09:48 UTC, lescadev commented on index.php
> +        <?php if ($iSUSet) { ?>
cf commentaire précédent

2020-02-24 09:48 UTC, lescadev commented on index.php
> +        <?php if ($isSUSet) { ?>
idem

2020-02-24 09:51 UTC, lescadev approved these changes

2020-02-24 09:52 UTC, minanass approved these changes

2020-02-24 09:53 UTC, CBaraka approved these changes

2020-02-24 09:55 UTC, merged